[build]
command = "zola build"
publish = "public"
ignore = "git update-index --skip-worktree .gitmodules || true"

[build.environment]
ZOLA_VERSION = "0.18.0"

[git]
# Disable submodule initialization
submodules = false

[context.production]
command = "zola build"

[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PREVIEW_URL"

[context.branch-deploy]
command = "zola build --base-url $DEPLOY_URL"
